# Generated by Django 4.0.1 on 2022-01-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0002_alter_book_publisheddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publishedDate',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
